# Generated by Django 3.0.4 on 2020-03-13 04:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='kindOf',
            field=models.CharField(choices=[('เชียงใหม่', 'เชียงใหม่'), ('กรุงเทพ', 'กรุงเทพ')], default='กรุงเทพ', max_length=20),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
