# Generated by Django 3.0.4 on 2020-03-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
