# Generated by Django 3.0.4 on 2020-03-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='touristattraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attraction.TouristAttraction'),
        ),
    ]
