# Generated by Django 3.0.4 on 2020-03-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0008_news_touristattraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.IntegerField()),
                ('rank_type', models.CharField(choices=[('ระดับจังหวัด', 'ระดับจังหวัด'), ('ระดับประเทศ', 'ระดับประเทศ')], default='ระดับประเทศ', max_length=100)),
                ('touristattraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.TouristAttraction')),
            ],
        ),
    ]
