# Generated by Django 3.0.4 on 2020-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0012_auto_20200320_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='touristattraction',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='news', width_field='width_field'),
        ),
    ]
