# Generated by Django 3.0.4 on 2020-03-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0013_auto_20200320_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='height_field',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='width_field',
            field=models.IntegerField(default=100),
        ),
    ]
