# Generated by Django 3.0.4 on 2020-03-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0014_auto_20200323_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristattraction',
            name='slug',
        ),
    ]
