# Generated by Django 3.0.4 on 2020-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0015_remove_touristattraction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
