# Generated by Django 3.0.4 on 2020-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0022_remove_touristattraction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='touristattractions',
            field=models.ManyToManyField(to='attraction.TouristAttraction'),
        ),
    ]
